### ISSUE TITLE
Cluster does not accept connections?

### ISSUE THREAD

**Issue by plorent** [gmr/alpine-rabbitmq-autocluster#1]
Using the CloudFormation stack - as is but running in eu-west-1, I see the clustering mechanism working as expected but I cannot make a connection from my client code (the management interface is available). Looking at the logs I get the following messages:

`=CRASH REPORT==== 6-Jun-2016::12:38:56 ===
  crasher:
    initial call: gen:init_it/6
    pid: <0.5973.3>
    registered_name: []
    exception exit: {amqp_error,internal_error,
                                "Interceptor: more than one module handles {set,1,16,16,8,80,48,\n                                           {[],[],[],[],[],[],[],[],[],[],[],\n                                            [],[],[],[],[]},\n                                           {{[],[],[],[],[],[],[],[],\n                                             ['basic.publish'],\n                                             [],[],[],[],[],[],[]}}}\n",
                                none}
      in function  gen_server2:init_it/6 (src/gen_server2.erl, line 601)
    ancestors: [<0.5970.3>,<0.5968.3>,<0.5962.3>,<0.5961.3>,<0.859.0>,
                  <0.858.0>,<0.857.0>,rabbit_sup,<0.82.0>]
    messages: []
    links: [<0.5970.3>]
    dictionary: [{process_name,
                      {rabbit_channel,
                          {<<"80.255.245.230:39333 -> 172.31.3.42:5672">>,
                           1}}}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2212
  neighbours:

=CRASH REPORT==== 6-Jun-2016::12:38:56 ===
  crasher:
    initial call: rabbit_reader:init/4
    pid: <0.5963.3>
    registered_name: []
    exception error: no match of right hand side value
                     {error,
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {{amqp_error,internal_error,
                            "Interceptor: more than one module handles {set,1,16,16,8,80,48,\n                                           {[],[],[],[],[],[],[],[],[],[],[],\n                                            [],[],[],[],[]},\n                                           {{[],[],[],[],[],[],[],[],\n                                             ['basic.publish'],\n                                             [],[],[],[],[],[],[]}}}\n",
                            none},
                           {child,undefined,channel,
                            {rabbit_channel,start_link,
                             [1,<0.5963.3>,<0.5971.3>,<0.5963.3>,
                              <<"80.255.245.230:39333 -> 172.31.3.42:5672">>,
                              rabbit_framing_amqp_0_9_1,
                              {user,<<"guest">>,
                               [administrator],
                               [{rabbit_auth_backend_internal,none}]},
                              <<"/">>,
                              [{<<"connection.blocked">>,bool,true},
                               {<<"authentication_failure_close">>,bool,true},
                               {<<"consumer_cancel_notify">>,bool,true},
                               {<<"publisher_confirms">>,bool,true},
                               {<<"basic.nack">>,bool,true}],
                              <0.5965.3>,<0.5972.3>]},
                            intrinsic,70000,worker,
                            [rabbit_channel]}}}},
                        [{rabbit_channel_sup,start_link,1,
                          [{file,"src/rabbit_channel_sup.erl"},{line,67}]},
                         {supervisor2,do_start_child_i,3,
                          [{file,"src/supervisor2.erl"},{line,437}]},
                         {supervisor2,handle_call,3,
                          [{file,"src/supervisor2.erl"},{line,463}]},
                         {gen_server,try_handle_call,4,
                          [{file,"gen_server.erl"},{line,629}]},
                         {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,661}]},
                         {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,240}]}]}}}
      in function  rabbit_reader:create_channel/2 (src/rabbit_reader.erl, line 916)
      in call from rabbit_reader:process_frame/3 (src/rabbit_reader.erl, line 972)
      in call from rabbit_reader:handle_input/3 (src/rabbit_reader.erl, line 1035)
      in call from rabbit_reader:recvloop/4 (src/rabbit_reader.erl, line 446)
      in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 428)
      in call from rabbit_reader:start_connection/4 (src/rabbit_reader.erl, line 386)
    ancestors: [<0.5961.3>,<0.859.0>,<0.858.0>,<0.857.0>,rabbit_sup,
                  <0.82.0>]
    messages: [{'EXIT',#Port<0.41801>,normal}]
    links: [<0.5961.3>]
    dictionary: [{process_name,
                      {rabbit_reader,
                          <<"80.255.245.230:39333 -> 172.31.3.42:5672">>}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 3992
  neighbours:

=SUPERVISOR REPORT==== 6-Jun-2016::12:38:56 ===
     Supervisor: {<0.5961.3>,rabbit_connection_sup}
     Context:    child_terminated
     Reason:     {badmatch,
                  {error,
                   {'EXIT',
                    {{badmatch,
                      {error,
                       {{amqp_error,internal_error,
                         "Interceptor: more than one module handles {set,1,16,16,8,80,48,\n                                           {[],[],[],[],[],[],[],[],[],[],[],\n                                            [],[],[],[],[]},\n                                           {{[],[],[],[],[],[],[],[],\n                                             ['basic.publish'],\n                                             [],[],[],[],[],[],[]}}}\n",
                         none},
                        {child,undefined,channel,
                         {rabbit_channel,start_link,
                          [1,<0.5963.3>,<0.5971.3>,<0.5963.3>,
                           <<"80.255.245.230:39333 -> 172.31.3.42:5672">>,
                           rabbit_framing_amqp_0_9_1,
                           {user,<<"guest">>,
                            [administrator],
                            [{rabbit_auth_backend_internal,none}]},
                           <<"/">>,
                           [{<<"connection.blocked">>,bool,true},
                            {<<"authentication_failure_close">>,bool,true},
                            {<<"consumer_cancel_notify">>,bool,true},
                            {<<"publisher_confirms">>,bool,true},
                            {<<"basic.nack">>,bool,true}],
                           <0.5965.3>,<0.5972.3>]},
                         intrinsic,70000,worker,
                         [rabbit_channel]}}}},
                     [{rabbit_channel_sup,start_link,1,
                       [{file,"src/rabbit_channel_sup.erl"},{line,67}]},
                      {supervisor2,do_start_child_i,3,
                       [{file,"src/supervisor2.erl"},{line,437}]},
                      {supervisor2,handle_call,3,
                       [{file,"src/supervisor2.erl"},{line,463}]},
                      {gen_server,try_handle_call,4,
                       [{file,"gen_server.erl"},{line,629}]},
                      {gen_server,handle_msg,5,
                       [{file,"gen_server.erl"},{line,661}]},
                      {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,240}]}]}}}}
     Offender:   [{pid,<0.5963.3>},
                  {name,reader},
                  {mfargs,
                      {rabbit_reader,start_link,
                          [<0.5962.3>,
                           {acceptor,{0,0,0,0,0,0,0,0},5672},
                           #Port<0.41801>]}},
                  {restart_type,intrinsic},
                  {shutdown,4294967295},
                  {child_type,worker}]

=SUPERVISOR REPORT==== 6-Jun-2016::12:38:56 ===
     Supervisor: {<0.5961.3>,rabbit_connection_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.5963.3>},
                  {name,reader},
                  {mfargs,
                      {rabbit_reader,start_link,
                          [<0.5962.3>,
                           {acceptor,{0,0,0,0,0,0,0,0},5672},
                           #Port<0.41801>]}},
                  {restart_type,intrinsic},
                  {shutdown,4294967295},
                  {child_type,worker}]`

Any idea what could be causing this?

**Comment by gmr** [comment]
Yeah, I ran into it myself over the weekend. It has to do with having two plugins installed that conflict with each other.
1. The images on Docker Hub are already updated and shouldn't have the problem. I ended up removing the node `rabbitmq_routing_node_stamp` plugin in the Dockerfile, in case you're extending it or have your own fork.
2. There is a ticket tracking the issue: [rabbitmq/rabbitmq-server #824](https://github.com/rabbitmq/rabbitmq-server/issues/824)

Sorry for the inconvenience.
