### ISSUE TITLE
Rabbit Users

### ISSUE THREAD

**Issue by tkd-hgoertz** [gmr/alpine-rabbitmq-autocluster#2]
How can I handle RabbitMQ Users?

**Comment by gmr** [comment]
What do you mean? As in how can you add them? 

If that's what you're going for, the default guest/guest user is enabled and you can use the management API to add them and change that one. You could also docker exec /bin/sh to get shell access in a running container to use `rabbitmqctl`.

**Comment by tkd-hgoertz** [comment]
I don't like guest/guest :) and know how to create users but is there an possibility to create users initial and change or deactivate the guest ?

**Comment by gmr** [comment]
You can extend the Dockerfile and do any of the following:
- Change/put your own `rabbitmq.config` adding guest/guest back to localhost only
- Use a definitions file to load in the users you want as part of the startup by placing the definitions file in the image and updating the `rabbitmq.config` to load the definitions file. See https://www.rabbitmq.com/management.html#configuration

Or once the container is running you could:
- Use the Management API as guest/guest to add your new users and remove then remove the guest/guest account
- Use `docker exec` to execute `rabbitmqctl` to add new users and remove `guest`.
